Repository burgersandbeers/beerbot, pull requests merged in 2020-10, with the labels that each got.

#1 Add base files
  .env-example
  .gitignore
  Gemfile
  Gemfile.lock
  bin/main.rb
  lib/bot.rb
Labels: hacktoberfest-accepted

#2 comando pong
  lib/bot.rb
Labels: hacktoberfest-accepted

#3 Add untappd integration
  Gemfile
  Gemfile.lock
  lib/beer.rb
  lib/bot.rb
Labels: hacktoberfest-accepted

#4 covid
  .env-example
  Gemfile
  Gemfile.lock
  lib/beer.rb
  lib/bot.rb
  lib/covid.rb
Labels: hacktoberfest-accepted

#5 consulta paraderos
  lib/bot.rb
  lib/paraderos.rb
Labels: hacktoberfest-accepted, paraderos

#6 servicio temblores
  lib/bot.rb
  lib/temblores.rb
Labels: hacktoberfest-accepted, temblores

#8 dato random
  lib/bot.rb
  lib/dato.rb
Labels: hacktoberfest-accepted

#9 horoscopo
  lib/bot.rb
  lib/horoscopo.rb
Labels: hacktoberfest-accepted

#10 Add procfile
  Procfile
Labels: hacktoberfest-accepted

#11 listado de micros por paradero
  lib/paraderos.rb
Labels: hacktoberfest-accepted, paraderos

#12 mejora en la impresion
  lib/bot.rb
  lib/saldoBip.rb
Labels: hacktoberfest-accepted, saldo-bip

#13 se agrega parametro al initialize
  lib/saldoBip.rb
Labels: hacktoberfest-accepted, saldo-bip

#14 Fix merge errors, add exception handling, update readme
  README.md
  bin/main.rb
  lib/bot.rb
Labels: hacktoberfest-accepted
